version: '3.4'

services:      
  novaweb.api:
    image: novaweb.api
    restart: always
    build:
      context: .
      dockerfile: NovaWeb.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "30123:80"
    networks:
      - novaweb-networks

networks:
  novaweb-networks:
    driver: bridge